## Demonstration of using Saxskit

In [29]:
import pandas as pd
import numpy as np

In [7]:
import saxskit

from saxskit.saxskit.saxs_classify import SaxsClassifier
from saxskit.saxskit.saxs_fit import profile_spectrum

In [11]:
# for example, a user has his data (one sample in 2016_saxs_data/R1/R1_1stcool_1_0001_dz_bgsub.csv)
# read an I_q array from .csv file:
df = pd.read_csv('2016_saxs_data/R1/R1_1stcool_1_0001_dz_bgsub.csv')

In [12]:
df.head()

# q (1/Angstrom)   Intensity (counts)
0             0.040          1198.428065
1             0.041          1175.669386
2             0.042          1155.045839
3             0.043          1133.378171
4             0.044          1110.756155

In [21]:
q_i = np.array(df)

In [24]:
# now we need to exctract the features from this data:
features = profile_spectrum(q_i)

In [26]:
features

OrderedDict([('q_Imax', 0.04000000476609962),
             ('Imax_over_Imean', 18.605887875876764),
             ('Imax_sharpness', 1.0379096113485911),
             ('logI_fluctuation', 5.377461795032489),
             ('logI_max_over_std', 2.9036342429056212)])

In [27]:
m = SaxsClassifier()

# problem: output of profile_spectrum is an ordered dictionary, 
# but classify() takes an array as input
# in paws we have SpectrumClassifier with:
#def run(self):
        #....
        #self.outputs['flags'] = c.classify(np.array(list(x.values())).reshape(1,-1))
        
        # should we have something like run() in saxskit?
        # I think, the next line could be to hard to understand for users:
result = m.classify(np.array(list(features.values())).reshape(1,-1))

/Users/kate/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [28]:
result

OrderedDict([('bad_data', (False, 0.99998793529385255)),
             ('form_factor_scattering',
              (array([ True], dtype=bool), 0.9999996942913687)),
             ('precursor_scattering',
              (array([False], dtype=bool), 0.77412891779678061)),
             ('diffraction_peaks',
              (array([False], dtype=bool), 0.87852247217004864))])